name: ukelonn CI and deploy build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
      with:
        persist-credentials: false
    - name: Set up maven and Java version
      uses: s4u/setup-maven-action@6c4e9964d4ecb8f1026310cd8618791fd51a8016
      with:
        java-version: 21
        maven-version: 3.9.11
    - name: Add ssh key
      run: |
          mkdir -p /home/runner/.m2
          cp .github/workflows/settings.xml /home/runner/.m2
          mkdir -p /home/runner/.ssh
          ssh-keyscan maven.bang.priv.no >> /home/runner/.ssh/known_hosts
          echo "$MAVEN_SSH_KEY" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
      env:
        MAVEN_SSH_KEY: ${{ secrets.MAVEN_SSH_KEY }}
    - name: Build with Maven
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent install coveralls:report sonar:sonar --file pom.xml --define repoToken="$COVERALLS_REPO_TOKEN" -Dsonar.projectKey=steinarb_ukelonn -Dsonar.organization=steinarb -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_SECRET }}
    - name: Deploy snapshot to maven repo
      run: mvn -B deploy -DskipTests=true
      env:
        REPO_USER: ${{ secrets.REPO_USER }}
